@startuml

artifact Application as app
note top: dotnet run Application -ConfigFolder="path/to/configFolder"

folder path/to/configFolder as folder{
    file appsettings.json as s1
    file appsettings.MyEnvironment.json as s2
    file NLog.json as l
    
    s1 -[hidden]-> s2
    s2 -[hidden]-> l
}

app -r-> s1
app -r-> s2
app -r-> l



@enduml