@startuml

start

:It's time to update rates;

fork
	:RateProvider1.GetRates();
	fork
	    :proxy.GetRates("RUB");
	fork again
	    :proxy.GetRates("USD");
	fork again
	    :proxy.GetRates("...");
	end fork
  fork again
	:RateProvider2.GetRates();
  fork again
    :RateProviderN.GetRates();
  end fork
:Process results;

end

@enduml