name: reader-client-ts-publish

env:
  CLIENT_FOLDER: scr/Reader/EasyRates.Reader.Client/ClientTs
  PCKG_NAME: reader-client-ts

on:
  push:
    branches: [non-existent-branch]
#on:
#  push:
#    branches: master
#    paths:
#      - "scr/Reader/EasyRates.Reader.Client/**"

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Get repository tags
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
        
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://npm.pkg.github.com'

    - name: Set package version
      run: |
        PCKG_VERSION=$(git describe --match "$PCKG_NAME/*" --abbrev=0)
        PCKG_VERSION=$(echo $PCKG_VERSION | cut -d'/' -f 2)
        PCKG_VERSION="$PCKG_VERSION.$GITHUB_RUN_NUMBER"
        echo $PCKG_VERSION
        yarn version --new-version $PCKG_VERSION
        
    - name: Install dependencies
      run: yarn install --cwd "${CLIENT_FOLDER}" --frozen-lockfile

    - name: Build
      run: yarn --cwd "${CLIENT_FOLDER}" build

    - name: Pack
      run: yarn --cwd "${CLIENT_FOLDER}" pack

    - name: Publish
      run: yarn --cwd "${CLIENT_FOLDER}" publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
